version: 0.2
phases:
  install: 
    runtime-versions:
      nodejs: 12
    commands:
      - echo "starting lambda build..."
      - npm install -g @angular/cli
      - (cd Threekit-Teknion-UI && npm install)
      - (cd Threekit-Teknion-UI && ng build --prod)
      - (cd functions/cancelImport && npm install)
      - (cd functions/createAndId_material && npm install)
      - (cd functions/importJobStatus && npm install)
      - (cd functions/orderExport && npm install)
      - (cd functions/parseXMLFromS3 && npm install)
      - (cd functions/process_API_assets && npm install)
      - (cd functions/process_API_Items && npm install)
      - (cd functions/process_API_Items_Error && npm install)
  build:
    commands:
      - echo "zipping functions..."
      - (cd functions/cancelImport && zip -r cancelImport.zip *)
      - (cd functions/createAndId_material && zip -r createAndIdMaterial.zip *)
      - (cd functions/importJobStatus && zip -r importJobStatus.zip *)
      - (cd functions/orderExport && zip -r orderExport.zip *)
      - (cd functions/parseXMLFromS3 && zip -r parseXMLFromS3.zip *)
      - (cd functions/process_API_assets && zip -r processAPIAssets.zip *)
      - (cd functions/process_API_Items && zip -r processAPIItems.zip *)
      - (cd functions/process_API_Items_Error && zip -r processAPIItemsError.zip *)
      - echo "done zipping functions, sending to aws..."
      - aws lambda update-function-code --function-name parseXMLFromS3-$environment --zip-file fileb://functions/parseXMLFromS3/parseXMLFromS3.zip
      - aws lambda update-function-code --function-name cancelImport-$environment --zip-file fileb://functions/cancelImport/cancelImport.zip
      - aws lambda update-function-code --function-name createAndId_material-$environment --zip-file fileb://functions/createAndId_material/createAndIdMaterial.zip
      - aws lambda update-function-code --function-name importJobStatus-$environment --zip-file fileb://functions/importJobStatus/importJobStatus.zip
      - aws lambda update-function-code --function-name orderExport-$environment --zip-file fileb://functions/orderExport/orderExport.zip
      - aws lambda update-function-code --function-name process_API_assets-$environment --zip-file fileb://functions/process_API_assets/processAPIAssets.zip
      - aws lambda update-function-code --function-name process_API_Items-$environment --zip-file fileb://functions/process_API_Items/processAPIItems.zip
      - aws lambda update-function-code --function-name process_API_Items_Error-$environment --zip-file fileb://functions/process_API_Items_Error/processAPIItemsError.zip
      - aws s3 cp Threekit-Teknion-UI/dist/Threekit-Teknion-UI s3://$S3_BUCKET_UI --recursive
      - echo "done sending to aws."
    