version: 0.2
phases:
  install: 
    runtime-versions:
      nodejs: 12
    commands:
      - echo "starting lambda build..."
      - npm install -g @angular/cli
      - (cd Threekit-Teknion-UI && npm install)
      - (cd Threekit-Teknion-UI && ng build --prod)
      - (cd functions/cancelImport && npm install)
      - (cd functions/createAndId_material && npm install)
      - (cd functions/importJobStatus && npm install)
      - (cd functions/orderExport && npm install)
      - (cd functions/parseXMLFromS3 && npm install)
      - (cd functions/process_API_assets && npm install)
      - (cd functions/process_API_Items && npm install)
      - (cd functions/process_API_Items_Error && npm install)
  build:
    commands:
      - echo "zipping functions..."
      - (cd functions && zip -r cancelImport.zip cancelImport)
      - (cd functions && zip -r createAndIdMaterial.zip createAndId_material)
      - (cd functions && zip -r importJobStatus.zip importJobStatus)
      - (cd functions && zip -r orderExport.zip orderExport)
      - (cd functions && zip -r parseXMLFromS3.zip parseXMLFromS3)
      - (cd functions && zip -r processAPIAssets.zip process_API_assets)
      - (cd functions && zip -r processAPIItems.zip process_API_Items)
      - (cd functions && zip -r processAPIItemsError.zip process_API_Items_Error)
      - echo "done zipping functions, sending to aws..."
      - aws lambda update-function-code --function-name parseXMLFromS3-$environment --zip-file fileb://functions/parseXMLFromS3.zip
      - aws lambda update-function-code --function-name cancelImport-$environment --zip-file fileb://functions/cancelImport.zip
      - aws lambda update-function-code --function-name createAndId_material-$environment --zip-file fileb://functions/createAndIdMaterial.zip
      - aws lambda update-function-code --function-name importJobStatus-$environment --zip-file fileb://functions/importJobStatus.zip
      - aws lambda update-function-code --function-name orderExport-$environment --zip-file fileb://functions/orderExport.zip
      - aws lambda update-function-code --function-name process_API_assets-$environment --zip-file fileb://functions/processAPIAssets.zip
      - aws lambda update-function-code --function-name process_API_Items-$environment --zip-file fileb://functions/processAPIItems.zip
      - aws lambda update-function-code --function-name process_API_Items_Error-$environment --zip-file fileb://functions/processAPIItemsError.zip
      - aws s3 cp Threekit-Teknion-UI/dist/Threekit-Teknion-UI s3://$S3_BUCKET_UI --recursive
      - echo "done sending to aws."
    