CREATE TABLE job (
	jid    			integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nm				varchar(255) NOT NULL,
	total_items		integer NOT NULL
);

CREATE TABLE job_item (
	jid				integer REFERENCES job (jid),	
	object_id		varchar(255) NOT NULL,
	item_type		varchar(255) NOT NULL
);

CREATE UNIQUE INDEX job_name_idx ON job (nm);