/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:199486d8-1dce-4a0e-b71c-b6f4d961487a",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_P8SSfEbD3",
    "aws_user_pools_web_client_id": "4604bo4ee9j6flqahf9of62n08",
    "oauth": {}
};


export default awsmobile;
